= Zcage 
:author: Carlos Neira 
:email: <cneirabustos@gmail.com>
:revnumber: v1.1
:revdate: 26.06.2018

Zcage is a container manager for Illumos based distributions inspired by FreeBSD's iocage and SmartOS's vmadm.  
It's intended to be easy to use with a simple command line syntax that's is straight forward to understand.


= Installation: Github

  * 'git clone  http://github.com/cneira/zcage.git'
  *  npm install -g zcage
  


= WARNING

This is work in progress. 

= EXAMPLES

* Create a container using virtual network interface _vnic0_ using ip: 192.168.1.225, netmask and 192.168.1.1 as gateway and only allowed to use 2GB of RAM. 
```bash
# zcage create --alias=test07 --net "vnic0|192.168.1.225/24|192.168.1.1" --ram 2gb  
```
Now you can reference the container by it's alias test07. If you don't provide an alias a UUID will be generated for the container.

* Update the container to allow it to use more ram if needed and restrict maximum lwps to 3000
```bash
# zcage rctl -z test07 --ram 6gb --max-lwps 3000 
```

* Destroy the container (cannot be undone)
```bash
# zcage destroy -z test07 
```

= FEATURES

* Ease of use
* Resource control
* Observability features
* Reference containers by UUID or alias
* Rapid container creation within seconds 
* Exclusive IP networking by default
* Brands sparse, ipkg, lipkg and lx available for container creation

